app/models/booking.rb
app/models/superpower.rb
app/models/user.rb
db/migrate/20190812152027_create_users.rb
db/migrate/20190812152253_create_bookings.rb
db/migrate/20190812153026_create_superpowers.rb
db/migrate/20190812153621_add_superpower_to_booking.rb
db/schema.rb
test/models/booking_test.rb
test/models/superpower_test.rb
test/models/user_test.rb

models created

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_banner.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/card.scss
app/controllers/superpowers_controller.rb
app/views/bookings/new.html.erb
app/views/bookings/show.html.erb
app/views/devise/confirmations/new.html.erb
app/views/layouts/application.html.erb
app/views/shared/_navbar.html.erb
app/views/superpowers/index.html.erb
app/views/superpowers/new.html.erb
app/views/superpowers/show.html.erb
config/routes.rb

created views for superpower

---

app/controllers/superpowers_controller.rb
app/views/superpowers/show.html.erb

missing show page

---

.gitignore
app/views/superpowers/index.html.erb
db/seeds.rb

picture added to seeds

---

app/assets/stylesheets/components/_banner.scss
app/views/superpowers/show.html.erb
db/schema.rb

show page fixed

---

app/assets/stylesheets/components/_banner.scss
app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/pages/_index.scss
app/assets/stylesheets/pages/_show.scss
app/views/layouts/application.html.erb
app/views/superpowers/show.html.erb

form front end

---

app/assets/stylesheets/components/_banner.scss
app/assets/stylesheets/components/_navbar.scss
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb
app/views/layouts/application.html.erb
app/views/superpowers/index.html.erb
app/views/superpowers/new.html.erb

Login page

---

app/assets/stylesheets/components/_banner.scss
app/assets/stylesheets/components/_navbar.scss
app/views/devise/registrations/new.html.erb
app/views/layouts/application.html.erb
app/views/superpowers/index.html.erb

New registration page

---

app/assets/stylesheets/components/_card.scss
app/views/devise/sessions/new.html.erb
app/views/superpowers/index.html.erb

Card section

---

app/assets/stylesheets/components/_banner.scss
db/seeds.rb

hi guys   i have changed the banner picture, please merge

banner picture changed

---

app/assets/stylesheets/components/_banner.scss
app/assets/stylesheets/components/_card.scss
app/assets/stylesheets/components/_font.scss
app/assets/stylesheets/components/_index.scss
app/views/layouts/application.html.erb
app/views/superpowers/index.html.erb
db/seeds.rb

added price, card photo changed

price tag added

---

app/controllers/pages_controller.rb
app/controllers/superpowers_controller.rb

home page redirect problem fixed

---

app/controllers/pages_controller.rb
app/controllers/superpowers_controller.rb
app/views/superpowers/show.html.erb

please merge, the euro sign for show page added

Show page euro sign

---

app/assets/stylesheets/components/_avatar.scss
app/assets/stylesheets/components/_banner.scss
app/assets/stylesheets/components/_card.scss
app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/config/_bootstrap_variables.scss
app/assets/stylesheets/config/_colors.scss
app/assets/stylesheets/pages/_show.scss
app/views/shared/_navbar.html.erb
app/views/superpowers/show.html.erb

Show page adjust

---

app/controllers/bookings_controller.rb
app/controllers/superpowers_controller.rb
app/views/bookings/new.html.erb
app/views/bookings/show.html.erb
app/views/superpowers/show.html.erb
config/routes.rb

Please merge - there will be conflicts though...

Booking form on showpage fixed and ugly booking showpage created

---

app/assets/stylesheets/pages/_show.scss

container of the index page fixed, please merge thanks!

container adjusted

---

app/assets/stylesheets/pages/_show.scss
app/views/shared/_navbar.html.erb
app/views/superpowers/index.html.erb

fixed the problem of container you can merge now Thomas!

Container problem fix

---

app/views/shared/_navbar.html.erb

hey thomas please merge    just changed the avatar pic thats all

changed avatar

---

app/assets/stylesheets/components/_card.scss

card picture fixed

---

app/assets/stylesheets/components/_banner.scss
app/assets/stylesheets/pages/_home.scss

please check it out and merge if you are happy, thanks

formhome branch

---

app/assets/stylesheets/components/_navbar.scss
app/views/shared/_navbar.html.erb
app/views/superpowers/index.html.erb
app/views/superpowers/show.html.erb

Clickable img

---

app/views/shared/_navbar.html.erb
app/views/superpowers/show.html.erb

the navbar is not stick to top anymore, please merge

sticky top of navbar gone

---

app/assets/stylesheets/pages/_index.scss
app/views/shared/_navbar.html.erb
app/views/superpowers/new.html.erb

drop down fixed

---

app/views/layouts/application.html.erb

url changed for pushing to heroku

title of the page changed

---

app/assets/stylesheets/components/_banner.scss
app/assets/stylesheets/pages/_dashboard.scss
app/assets/stylesheets/pages/_index.scss
app/views/dashboards/show.html.erb

hi i updated the dashboard please merge!

dashboard ready

---

app/assets/stylesheets/pages/_dashboard.scss
app/views/dashboards/show.html.erb

dashboard page style fixed

---

app/assets/stylesheets/components/_card.scss
app/assets/stylesheets/components/_navbar.scss
app/views/superpowers/index.html.erb

style of index fixed

---

app/assets/stylesheets/components/_confirmation.scss
app/views/bookings/show.html.erb
app/views/pages/home.html.erb

Please merge, should be correct now

added disappeared css corrections
